apiVersion: v1
kind: Service
metadata:
  name: ollama-tinyllama
  namespace: aiops
  labels:
    app: ollama-tinyllama
spec:
  selector:
    app: ollama-tinyllama
  ports:
    - port: 11434
      targetPort: 11434
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-tinyllama
  namespace: aiops
  labels:
    app: ollama-tinyllama
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ollama-tinyllama
  template:
    metadata:
      labels:
        app: ollama-tinyllama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_MODEL
              value: "tinyllama:latest"
          volumeMounts:
            - name: ollama-models
              mountPath: /root/.ollama
          command: ["/bin/sh"]
          args:
            - -c
            - |
              ollama serve &
              sleep 3 && ollama run $OLLAMA_MODEL && wait
          readinessProbe:
            tcpSocket:
              port: 11434
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
      volumes:
        - name: ollama-models
          emptyDir: {}
