apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollamaverse-py-backend
  namespace: aiops
  labels:
    app: ollamaverse-py-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ollamaverse-py-backend
  template:
    metadata:
      labels:
        app: ollamaverse-py-backend
    spec:
      containers:
        - name: ollamaverse-py-backend
          image: 976193257685.dkr.ecr.ap-south-1.amazonaws.com/ollamaverse-py-backend:1.12
          ports:
            - containerPort: 5001
          env:
            - name: FLASK_ENV
              value: "production"
            - name: OLLAMA_HOST
              value: "http://ollama-smollm2.aiops.svc.cluster.local:11434"
              # 👆 or change to ollama-tinyllama if you want that model instead
          readinessProbe:
            httpGet:
              path: /models
              port: 5001
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /models
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 20
