apiVersion: v1
kind: Service
metadata:
  name: ollamaverse-backend-service
  namespace: aiops
spec:
  type: ClusterIP
  selector:
    app: ollamaverse-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000