config:
  clients:
    - url: http://3.108.239.119:3100/loki/api/v1/push

  positions:
    filename: /run/promtail/positions.yaml  # writable path

  server:
    http_listen_port: 3101

  scrape_configs:
    - job_name: kubernetes-pods
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_name]
          regex: 'mongodb|ollama-smollm2|ollama-tinyllama|ollamaverse-backend|ollamaverse-frontend|ollamaverse-py-backend|ollamaverse-tokenapi|redis'
          action: keep
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_container_name]
          target_label: container

