apiVersion: v1
kind: Secret
metadata:
  name: elastic-creds
  namespace: logging
type: Opaque
data:
  # The username 'elastic' base64 encoded (likely correct)
  username: ZWxhc3RpYw== 
  # This value is IGNORED by the DaemonSet below for testing
  password: Snc3aUd5bVoqX2Y0MWpiX1lidWY=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  parsers.conf: |
    # ==================================
    # Docker Parser
    # ==================================
    [PARSER]
        Name   docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep On

    # ==================================
    # Time format from EKS/GKE/AKS
    # ==================================
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%NZ
        Time_Keep On

    # ==================================
    # CRI Parser (alternative for some K8s runtimes)
    # ==================================
    [PARSER]
        Name   cri
        Format regex
        Regex  ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<log>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep On

  input-kubernetes.conf: |
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.*
        Mem_Buf_Limit    5MB
        Refresh_Interval 5

  filter-kubernetes.conf: |
    [FILTER]
        Name              kubernetes
        Match             kube.*
        Kube_URL          https://kubernetes.default.svc:443
        Merge_Log         On
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name    record_modifier
        Match   kube.*
        Record  cluster my-eks-cluster

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            ${ELASTIC_HOST}
        Port            ${ELASTIC_PORT}
        HTTP_User       ${ELASTIC_USER}
        HTTP_Passwd     ${ELASTIC_PASS}
        Index           fluentbit-%Y.%m.%d
        Type            _doc
        Time_Key        @timestamp
        Logstash_Format On
        Retry_Limit     False
        tls             On
        tls.verify      Off
        Suppress_Type_Name  On
        # For production set tls.verify On and use tls.ca_file to point to CA file
        tls.ca_file    /dev/null

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-role
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-role
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: logging

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit
  template:
    metadata:
      labels:
        k8s-app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      tolerations:
        - operator: "Exists"
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.2
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTIC_HOST
              value: "65.2.131.128"
            - name: ELASTIC_PORT
              value: "9200"
            - name: ELASTIC_USER
              valueFrom:
                secretKeyRef:
                  name: elastic-creds
                  key: username
            - name: ELASTIC_PASS
              value: "Sr7iGymZ*_f41jb_Ybuf" # <-- TEMPORARY TEST: Password added in plain text
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: elastic-ca
              mountPath: /fluent-bit/tls
              readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 50Mi
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
            items:
              - key: fluent-bit.conf
                path: fluent-bit.conf
              - key: input-kubernetes.conf
                path: input-kubernetes.conf
              - key: filter-kubernetes.conf
                path: filter-kubernetes.conf
              - key: output-elasticsearch.conf
                path: output-elasticsearch.conf
              - key: parsers.conf
                path: parsers.conf
        - name: elastic-ca
          secret:
            secretName: elastic-ca
            optional: true