apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadtest-cron
  namespace: aiops
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      ttlSecondsAfterFinished: 300
      template:
        spec:
          serviceAccountName: loadtest-cron-sa
          restartPolicy: Never
          containers:
            - name: loadtest
              image: 976193257685.dkr.ecr.ap-south-1.amazonaws.com/ollamaverse-loadtest-cron:1.6
              env:
                # --- AWS_REGION from ConfigMap ---
                - name: AWS_REGION
                  valueFrom:
                    configMapKeyRef:
                      # Reference the ConfigMap created in Step 1
                      name: loadtest-config
                      # Reference the key name within the ConfigMap
                      key: aws_region 
                # --- S3_BUCKET from ConfigMap ---
                - name: S3_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      name: loadtest-config
                      key: s3_bucket
              # resources: (omitted for brevity)
              # ...