apiVersion: v1
kind: Service
metadata:
  name: ollama-smollm2
  namespace: aiops
  labels:
    app: ollama-smollm2
spec:
  selector:
    app: ollama-smollm2
  ports:
    - port: 11434
      targetPort: 11434
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-smollm2
  namespace: aiops
  labels:
    app: ollama-smollm2
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ollama-smollm2
  template:
    metadata:
      labels:
        app: ollama-smollm2
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_MODEL
              value: "smollm2:135m-instruct-q8_0"
          volumeMounts:
            - name: ollama-models
              mountPath: /root/.ollama
          command: ["/bin/sh"]
          args:
            - -c
            - |
              # Start Ollama API server in the background
              ollama serve &
              sleep 5
              # Preload and prepare the model so API can serve it
              ollama run "$OLLAMA_MODEL"
              wait
          readinessProbe:
            tcpSocket:
              port: 11434
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
      volumes:
        - name: ollama-models
          emptyDir: {}
